export type articleProps = {
  id: string,
  handle: string,
  title: string,
  category: string,
  subtitle: string,
  information: string,
  createdDate?: string, // Optional field for created date
};

export const dummyArticles = [{
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
}, {
  id: '1',
  handle: 'article1',
  title: 'title...',
  category: 'cat..',
  subtitle: 'sub...',
  information: 'information....'
},];